root = "."
tmp_dir = "./tmp"

[build]
cmd = "go build -gcflags='all=-N -l' -o ./tmp/main ./cmd"
bin = "./tmp/main"
full_bin = "dlv exec --headless --listen=:40000 --api-version=2 --accept-multiclient ./tmp/main"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp"]
include_dir = ["cmd","infra",'repository','service','adapter','data']
exclude_file = []
log = "tmp/air.log"
# delay = 1000 # ms
stop_on_error = false
send_interrupt = false
# kill_delay = 500 # ms


[log]
time = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true
